package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// ════════════════════════════════════════════════════════════════
// ENV FILE GENERATION
// ════════════════════════════════════════════════════════════════

func createEnvFile(cfg *Config) {
	adminNotifEnabled := "false"
	if cfg.AdminNotificationsChatID != "" {
		adminNotifEnabled = "true"
	}
	adminNotifChatID := cfg.AdminNotificationsChatID
	if adminNotifChatID == "" {
		adminNotifChatID = ""
	}

	if cfg.KeepExistingVolumes && cfg.OldPostgresPassword != "" {
		cfg.PostgresPassword = cfg.OldPostgresPassword
	}

	// Basic Auth строки
	basicAuthLines := "#REMNAWAVE_USERNAME=\n#REMNAWAVE_PASSWORD="
	if cfg.RemnawaveAuthType == "basic_auth" {
		basicAuthLines = fmt.Sprintf("REMNAWAVE_USERNAME=%s\nREMNAWAVE_PASSWORD=%s", cfg.RemnawaveUsername, cfg.RemnawavePassword)
	}

	// Webhook строки — закомментировать если пустые
	webhookURLLine := "#WEBHOOK_URL="
	if cfg.WebhookURL != "" {
		webhookURLLine = fmt.Sprintf("WEBHOOK_URL=%s", cfg.WebhookURL)
	}

	webhookSecretLine := "#WEBHOOK_SECRET_TOKEN="
	if cfg.WebhookSecretToken != "" {
		webhookSecretLine = fmt.Sprintf("WEBHOOK_SECRET_TOKEN=%s", cfg.WebhookSecretToken)
	}

	// Secret Key — закомментировать если пустой
	secretKeyLine := "#REMNAWAVE_SECRET_KEY="
	if cfg.RemnawaveSecretKey != "" {
		secretKeyLine = fmt.Sprintf("REMNAWAVE_SECRET_KEY=%s", cfg.RemnawaveSecretKey)
	}

	cabinetJWTSecret := generateToken()

	env := fmt.Sprintf(`# ===============================================
# REMNAWAVE BEDOLAGA BOT CONFIGURATION
# ===============================================
# Generated by bedolaga_installer v%s at %s
# ===============================================
# Раскомментируйте нужные настройки и укажите значения

# ===== TELEGRAM BOT (ОБЯЗАТЕЛЬНО) =====
BOT_TOKEN=%s
ADMIN_IDS=%s
SUPPORT_USERNAME=%s

# ===== DATABASE (ОБЯЗАТЕЛЬНО) =====
DATABASE_MODE=auto
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=remnawave_bot
POSTGRES_USER=remnawave_user
POSTGRES_PASSWORD=%s
REDIS_URL=redis://redis:6379/0

# ===== REMNAWAVE API (ОБЯЗАТЕЛЬНО) =====
REMNAWAVE_API_URL=%s
REMNAWAVE_API_KEY=%s
REMNAWAVE_AUTH_TYPE=%s
%s
%s

# ===== BOT MODE =====
BOT_RUN_MODE=%s
%s
WEBHOOK_PATH=/webhook
%s

# ===== WEB API =====
WEB_API_ENABLED=%s
WEB_API_HOST=0.0.0.0
WEB_API_PORT=8080
WEB_API_DEFAULT_TOKEN=%s

# ===== LOCALIZATION =====
DEFAULT_LANGUAGE=ru
AVAILABLE_LANGUAGES=ru,en,ua,zh,fa
TZ=Europe/Moscow

# ===== BASIC SETTINGS =====
SALES_MODE=tariffs
TRIAL_DURATION_DAYS=3
TRIAL_TRAFFIC_LIMIT_GB=10
DEFAULT_DEVICE_LIMIT=3

# ===============================================
# OPTIONAL SETTINGS (раскомментируйте при необходимости)
# ===============================================

# ===== SUPPORT SYSTEM =====
#SUPPORT_MENU_ENABLED=true
#SUPPORT_SYSTEM_MODE=both
#SUPPORT_TICKET_SLA_ENABLED=false
#SUPPORT_TICKET_SLA_MINUTES=60

# ===== CABINET =====
#CABINET_ENABLED=false
#CABINET_URL=
#CABINET_JWT_SECRET=%s

# ===== NOTIFICATIONS =====
#ADMIN_NOTIFICATIONS_ENABLED=%s
#ADMIN_NOTIFICATIONS_CHAT_ID=%s
#ADMIN_NOTIFICATIONS_TOPIC_ID=
#ADMIN_NOTIFICATIONS_TICKET_TOPIC_ID=
#ADMIN_NOTIFICATIONS_NALOG_TOPIC_ID=
#ADMIN_REPORTS_ENABLED=false
#ADMIN_REPORTS_CHAT_ID=
#ADMIN_REPORTS_TOPIC_ID=

# ===== SMTP =====
#SMTP_HOST=
#SMTP_PORT=587
#SMTP_USER=
#SMTP_PASSWORD=
#SMTP_FROM_EMAIL=

# ===== TRAFFIC MONITORING =====
#TRAFFIC_FAST_CHECK_ENABLED=false
#TRAFFIC_DAILY_CHECK_ENABLED=false

# ===== CHANNEL SUBSCRIPTION =====
#CHANNEL_SUB_ID=
#CHANNEL_IS_REQUIRED_SUB=false
#CHANNEL_LINK=

# ===== REMNAWAVE EXTENDED =====
#REMNAWAVE_CADDY_TOKEN=
#REMNAWAVE_USER_DESCRIPTION_TEMPLATE="Bot user: {full_name} {username}"
#REMNAWAVE_USER_USERNAME_TEMPLATE="user_{telegram_id}"
#REMNAWAVE_AUTO_SYNC_ENABLED=false

# ===== REMNAWAVE WEBHOOKS =====
#REMNAWAVE_WEBHOOK_ENABLED=false
#REMNAWAVE_WEBHOOK_PATH=/remnawave-webhook
#REMNAWAVE_WEBHOOK_SECRET=

# ===== TRIAL & SUBSCRIPTION =====
#TRIAL_TARIFF_ID=0
#TRIAL_PAYMENT_ENABLED=false
#MAX_DEVICES_LIMIT=15
#DEFAULT_TRAFFIC_LIMIT_GB=100
#DEFAULT_TRAFFIC_RESET_STRATEGY=MONTH

# ===== TRAFFIC =====
#TRAFFIC_SELECTION_MODE=selectable
#TRAFFIC_TOPUP_ENABLED=true
#TRAFFIC_PACKAGES_CONFIG="5:2000:false,10:3500:false,25:7000:false,50:11000:true,100:15000:true"

# ===== SUBSCRIPTION PERIODS =====
#AVAILABLE_SUBSCRIPTION_PERIODS=30,90,180
#AVAILABLE_RENEWAL_PERIODS=30,90,180

# ===== PRICES (kopecks) =====
#BASE_SUBSCRIPTION_PRICE=0
#PRICE_30_DAYS=10000
#PRICE_90_DAYS=36900
#PRICE_180_DAYS=69900
#PRICE_PER_DEVICE=10000
#PRICE_TRAFFIC_UNLIMITED=20000

# ===== REFERRAL =====
#REFERRAL_PROGRAM_ENABLED=true
#REFERRAL_MINIMUM_TOPUP_KOPEKS=10000
#REFERRAL_COMMISSION_PERCENT=25

# ===== AUTOPAY =====
#ENABLE_AUTOPAY=false
#AUTOPAY_WARNING_DAYS=3,1

# ===== PAYMENT: TELEGRAM STARS =====
#TELEGRAM_STARS_ENABLED=true
#TELEGRAM_STARS_RATE_RUB=1.79

# ===== PAYMENT: YOOKASSA =====
#YOOKASSA_ENABLED=false
#YOOKASSA_SHOP_ID=
#YOOKASSA_SECRET_KEY=
#YOOKASSA_RETURN_URL=

# ===== PAYMENT: CRYPTOBOT =====
#CRYPTOBOT_ENABLED=false
#CRYPTOBOT_API_TOKEN=
#CRYPTOBOT_WEBHOOK_SECRET=

# ===== PAYMENT: OTHER =====
#TRIBUTE_ENABLED=false
#HELEKET_ENABLED=false
#MULENPAY_ENABLED=false
#PAL24_ENABLED=false
#PLATEGA_ENABLED=false
#FREEKASSA_ENABLED=false
#KASSA_AI_ENABLED=false
#WATA_ENABLED=false
#CLOUDPAYMENTS_ENABLED=false

# ===== INTERFACE =====
#ENABLE_LOGO_MODE=true
#LOGO_FILE=vpn_logo.png
#MAIN_MENU_MODE=default
#CONNECT_BUTTON_MODE=miniapp_subscription

# ===== MINIAPP =====
#MINIAPP_STATIC_PATH=miniapp
#MINIAPP_SERVICE_NAME_RU=Bedolaga VPN

# ===== MONITORING =====
#MONITORING_INTERVAL=60
#ENABLE_NOTIFICATIONS=true

# ===== MAINTENANCE =====
#MAINTENANCE_MODE=false

# ===== BACKUPS =====
#BACKUP_AUTO_ENABLED=true
#BACKUP_TIME=03:00
#BACKUP_MAX_KEEP=7
#BACKUP_SEND_ENABLED=false
#BACKUP_SEND_CHAT_ID=
#BACKUP_SEND_TOPIC_ID=

# ===== LOGGING =====
#LOG_LEVEL=INFO
#LOG_ROTATION_ENABLED=false
#LOG_ROTATION_CHAT_ID=
#LOG_ROTATION_TOPIC_ID=

# ===== BAN SYSTEM =====
#BAN_SYSTEM_ENABLED=false

# ===== CONTESTS =====
#CONTESTS_ENABLED=false

# ===== BLACKLIST =====
#BLACKLIST_CHECK_ENABLED=false
`,
		appVersion, time.Now().Format("2006-01-02 15:04:05"),
		cfg.BotToken, cfg.AdminIDs, cfg.SupportUsername,
		cfg.PostgresPassword,
		cfg.RemnawaveAPIURL, cfg.RemnawaveAPIKey, cfg.RemnawaveAuthType,
		basicAuthLines, secretKeyLine,
		cfg.BotRunMode, webhookURLLine, webhookSecretLine,
		cfg.WebAPIEnabled, cfg.WebAPIDefaultToken,
		cabinetJWTSecret, adminNotifEnabled, adminNotifChatID,
	)

	envPath := filepath.Join(cfg.InstallDir, ".env")
	if err := os.WriteFile(envPath, []byte(env), 0600); err != nil {
		globalProgress.fail("Ошибка записи .env: " + err.Error())
		os.Exit(1)
	}
	globalProgress.done("Файл .env создан")
}
